### ISSUE TITLE
llama3.2-1B-CC

### ISSUE THREAD

**Issue by taishan1994** [microsoft/LLM2CLIP#18]
I would like to ask which vision model corresponds to Llama3.2-1B-CC?

**Comment by Yif-Yang** [comment]
We will release tomorrow

**Comment by taishan1994** [comment]
> We will release tomorrow

thank you

**Comment by raytrun** [comment]
The corresponding vision is right [here.](https://huggingface.co/microsoft/LLM2CLIP-Llama3.2-1B-EVA02-L-14-336)

**Comment by taishan1994** [comment]
> The corresponding vision is right [here.](https://huggingface.co/microsoft/LLM2CLIP-Llama3.2-1B-EVA02-L-14-336)

i got it, thanks
