### ISSUE TITLE
Confusions about original clip text-encoder context window length

### ISSUE THREAD

**Issue by happywinder** [microsoft/LLM2CLIP#21]
I found you solve a problem **Limited Context Window: The text encoder has a short context window of only 77 tokens, which restricts its understanding of lengthy inputs.**
but original clip text encoder is gpt-2 right？Or you mean long range dependency questions.

**Comment by Yif-Yang** [comment]
The original CLIP is indeed based on GPT-2, but you can check their details: during training, they truncate to a maximum of 77 tokens. For example, works like LongCLIP also focus on the maximum encoding length of the text part through view interpolation. What we have enabled is the ability to handle long-range dependencies and a better text understanding capability.

**Comment by happywinder** [comment]
Thx for your reply!

**Comment by ly1998117** [comment]
> The original CLIP is indeed based on GPT-2, but you can check their details: during training, they truncate to a maximum of 77 tokens. For example, works like LongCLIP also focus on the maximum encoding length of the text part through view interpolation. What we have enabled is the ability to handle long-range dependencies and a better text understanding capability.

In your training code, it looks like the tokenizer's context length is still 77 tokens. Does this mean the text encoder's context window in the Llama3.1-8B-Siglip2-So-L-14-224 model is still limited? If so, could this still constrain the model's ability to understand longer texts?
